### PR TITLE
Jmkelly fwise xunit upgrade with shared docstore

### PR DESCRIPTION
**Pull request by jmkelly**

### CODE REVIEW

**Comment by jmkelly** [comment]
Sorry about coming in over the top, I didn't realise, but I needed these changes in today for a project at work.

**Comment by fwise** [comment]
Taking a look at IdentityFactory first, replacing the Dictionary with ConcurrentDictionary is not going to fix the issue.  You'll also need to change how the dictionary is accessed and written to.  Something along these lines should do it.

```csharp
static bool TryGetIdProperty(object value, out PropertyInfo propertyInfo)
{
    var type = value.GetType();

    propertyInfo = _keyCache.GetOrAdd(type, typeofValue =>
    {
        return typeofValue.GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(x => x.Name.Equals("id", StringComparison.OrdinalIgnoreCase))
            .Where(x => x.PropertyType == typeof (Guid))
            .FirstOrDefault(x => x.CanRead && x.CanWrite);
    });

    return (propertyInfo != null);
}
```

**Comment by fwise** [comment]
My apologies, I think I'm actually incorrect.  All methods on ConcurrentDictionary are thread-safe.  My snippet above would just be a code simplification.

**Comment by jmkelly** [comment]
Tidied up in https://github.com/YoloDev/elephanet/commit/fc91d4c2dbdd5f4955ca5a0434b12694d1b41f2f

**Pull request merged**
